### ISSUE TITLE
Feature: User can search for an anime 

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can type in a title of an Anime in the search bar and see results matching that title.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="139" alt="Screen Shot 2021-09-20 at 3 51 17 PM" src="https://user-images.githubusercontent.com/87718271/134086850-cc3cb6f9-bfa8-476d-a901-4a68b62c4647.png">
<img width="140" alt="Screen Shot 2021-09-20 at 3 51 26 PM" src="https://user-images.githubusercontent.com/87718271/134086860-e5bf8579-ec8f-4aa3-a2b0-7811b72739be.png">

<img width="462" alt="Screen Shot 2021-09-20 at 4 35 17 PM" src="https://user-images.githubusercontent.com/87718271/134090170-1857910c-e38d-4dec-b5de-74462dcbcca5.png">
<img width="459" alt="Screen Shot 2021-09-20 at 4 35 24 PM" src="https://user-images.githubusercontent.com/87718271/134090172-0bdc4f41-fec2-4c5f-b78f-ade5ce6dbcd6.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] ... 
- [x] Add a div[data-view='search-page'] to HTML 
- [x] Add a search bar 
- [x] Add a nav bar on the bottom of the page 
- [x] Add a div[data-view='search-results']
- [x] Add an empty unordered list to div[data-view='search-results']
- [x] Add dummy anime search results to the unordered list
- [x] Define a function that takes an anime object as a parameter and returns a DOM tree that matches a dummy anime search result
- [x] Create a function to switch views based on data-view attribute
- [x] Listen for clicks on the search icon and:
  - [x] Define a function that opens a GET request from Jikan API for a string, the value in search bar
  - [x] Listen for 'load' event on the request object and have a function that loops through the first 5 results from the response and calls the function to create a DOM tree for each result and appends it to the page.
  - [x] Call switch views function
  - [x] Fill searchbar in search-results view with search value
- [x] Listen for clicks on searchbar in results
  - [x] Clear dom tree for current results
  - [x] Call the function for on search  
- [x] Listen to clicks on search icon
  - [x] clear dom tree for current results
  - [x] call switch views function to switch to search-page view
- [x] Remove example HTML anime results once search results are successfully appending to the page
- [x] Ensure it looks good on mobile and desktop

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
