### ISSUE TITLE
Feature: User can set priority when adding

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#11]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set priority when adding to their watch list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can set priority when adding to their watch list from the search results page 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2021-09-24 at 3 07 20 PM](https://user-images.githubusercontent.com/87718271/134744551-0fd1b6d4-e211-413e-99f9-e130cd94fcd0.png)
![Screen Shot 2021-09-24 at 3 07 32 PM](https://user-images.githubusercontent.com/87718271/134744553-93a373ff-859c-423e-a853-462a267b88ed.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add to createResult function to render anime results in search results with 'priority' and up arrow icons
- [x] Alter setPriority function to be able to set priority to an anime in 'search-results' view and 'watch-list' view
- [x] Listen for clicks on searchResults and
  - [x] Call the set priority function 
- [x] Remove renderWatchList function from setPriority function so that setting priority on search Results does not switch to 'watch list' immediately after setting priority, but switches on 'add' click  
- [x] Create separate function for setting priority in 'watch-list' view that calls setPriority and renderWatchList()
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
