### ISSUE TITLE
Feature: User can add anime to an in progress list

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#17]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add anime from their watch list, to an in progress watch list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add anime from their watch list, to an in progress watch list to keep track of anime they are currently watching

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="624" alt="Screen Shot 2021-09-30 at 4 58 25 PM" src="https://user-images.githubusercontent.com/87718271/135545929-01281413-b281-49cd-bc11-9fdd3bb0b666.png">
<img width="623" alt="Screen Shot 2021-09-30 at 4 58 52 PM" src="https://user-images.githubusercontent.com/87718271/135545949-d1608c1b-5e6f-4f5f-8c2b-4057732d9224.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a property inProgress to data model as an empty array
- [x] Alter createResult function to add a 'Watch' button to entries in watchList 
- [x] Listen for clicks on the watchList ul and:
  - [x] if the event.target is not a button, return
  - [x] if the event.target matches '.watch' using the element.matches()
  - [x] get the selected anime result in the DOM using .closest 
    - [x] loop through data.watchlist 
      - [x] if the value of the id attribute of the event.target is equal to the mal_id of the anime object in data.watchlist, add anime object to data.inProgress
    - [x] remove anime object from dom
    - [x] delete anime obj from data.watchList
- [x] Delete deleteResult function 
- [x] Create a div[data-view="in-progress"]
- [x] Add an empty ul
- [x] Add a header to this div with message if the in progress list is empty
- [x] Add a vector div and "In Progress" header to div[data-view="in-progress"]
- [x] Add an icon for in-progress view to navbars
- [x] Listen for clicks on the in-progress icon and
  - [x] call switchViews function to switch to in-progress view
  - [x] Call renderAnimeList function
- [x] Create a renderInProgress function that loops through data.inProgress and calls createResult func and appends each to the in-progress ul
- [x] Edit renderWatchList function to be able to render watchList and inProgressList depending on data.view
- [x] Edit setPriority function to be able to set priority within in progress view
- [x] Edit createResult function to render anime results in in progress view with just remove button
- [x] - [x] check if data.inProgressList is empty and set the message header to view if it is
- [x] Add to clearResults function to clear in progress list dom tree 
- [x] Edit watchListOptions function to be able to delete an anime result from in progress list as well
- [x] Listen for clicks on the inProgressList ul and
  - [x] call watchListOptions function
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
