### ISSUE TITLE
Feature: User can log their progress till completion of an anime

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#19]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log their progress till completion of anime

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can log their progress till completion of anime in their In Progress list
## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="621" alt="Screen Shot 2021-10-01 at 5 33 51 PM" src="https://user-images.githubusercontent.com/87718271/135698176-359e52d1-5168-4f92-9dd9-be5fca90301c.png">
<img width="536" alt="Screen Shot 2021-10-01 at 5 37 00 PM" src="https://user-images.githubusercontent.com/87718271/135698179-e898db3e-69c4-4dfa-be76-0f267ad13996.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Edit addResult function to add a 'progress' property set to number 0 when a anime is added 
- [x] Create dummy entry in inProgressList for anime result with progress bar, add and minus buttons, and episode on and total episodes
- [x] Edit createResult function for when data.view is inProgress to match dummy entry instead of "Synopsis", using animeObj.episodes property (number)
- [x] Create function for updating progress bar and current episode number
  - [x] Create a variable with a value (%) to increment by, by dividing 100% by the number of episodes in the anime
  - [x] Get current episode number, currEpisodeNum
  - [x]  If the passed value is 'dec' subtract one from currEpisodeNum and if 'inc' add one to currEpisodeNum
  - [x] Set the width, using element.style, of the progress bar's fill div to the currEpisodeNum * the increment value 
  - [x] Set text content of DOM element 'episode on' to currEpisodeNum
  - [x] Set progress property of animeObject to the new value of currEpisodeNum
- [x] Listen for clicks on the inProgressList and 
  - [x]  if the event.target does not match '.inc-button' or 'dec-button', return
  - [x]  if event.target.matches '.inc-button' call updateProgress function and inc currEpisode and progressbar
  - [x]  else if event.target.matches '.dec-button' call updateProgress function and dec currEpisode and progressBar
- [x] Ensure progress bar and current episode num persist after reload
- [x] ...
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
