### ISSUE TITLE
Feature: User can add an anime to their watch list

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#2]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can add an anime to their watch list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can add an anime from their search results to their watch list 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="139" alt="Screen Shot 2021-09-20 at 3 55 16 PM" src="https://user-images.githubusercontent.com/87718271/134087110-1b986688-831a-4a1d-ad1d-b1c792ed42b7.png">

<img width="139" alt="Screen Shot 2021-09-20 at 3 55 23 PM" src="https://user-images.githubusercontent.com/87718271/134087133-f01a0961-4fb7-473c-9685-32011ca1fecd.png">

<img width="462" alt="Screen Shot 2021-09-20 at 4 35 17 PM" src="https://user-images.githubusercontent.com/87718271/134090257-fd92914e-f8d9-418c-bf68-7afc59e184fc.png">
<img width="460" alt="Screen Shot 2021-09-20 at 4 35 57 PM" src="https://user-images.githubusercontent.com/87718271/134090264-b38c4dbe-931b-45b5-a34c-172410b91821.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a property searchList to data model as an empty array
- [x] Add a property watchList to data model as an empty array
- [x] Add to onSearch function to add each anime result object to searchList property
- [x] Create a dummy anime result and add a 'add' button to the anime result
- [x] Add to createResult function to render this button on each result as well
- [x] Add an id to each search result on the li, assigned to mal_id property from anime result obj
- [x] Listen for clicks on the 'results' ul
  - [x] if the event.target is not a 'BUTTON', return
  - [x] loop through searchList in data, if the mal_id of the event.target matches the searchList mal_id
  - [x] Add the anime result object in searchList to watchList in data model
- [x] Ensure searchList in data model is cleared upon new search
- [x] Ensure watchList is saving to local storage and added anime result objects are still there after reload
- [x] Ensure page reloads into same page.

- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
