### ISSUE TITLE
Feature: User can view the anime in their watch list

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view anime in their watch list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to view the anime they have added from their search results in a list

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="138" alt="Screen Shot 2021-09-20 at 3 58 01 PM" src="https://user-images.githubusercontent.com/87718271/134087350-08658d49-63e6-41ac-9692-67af12a9c1c2.png">
<img width="137" alt="Screen Shot 2021-09-20 at 3 58 08 PM" src="https://user-images.githubusercontent.com/87718271/134087364-28497bb8-7293-408e-8727-df035f7e77db.png">

<img width="459" alt="Screen Shot 2021-09-20 at 4 37 22 PM" src="https://user-images.githubusercontent.com/87718271/134090351-8003739d-94e7-4891-8590-b074cb5fdff4.png">
<img width="460" alt="Screen Shot 2021-09-20 at 4 37 28 PM" src="https://user-images.githubusercontent.com/87718271/134090361-3479eb64-9c58-4a3a-9f63-7b3b90b64353.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a div[data-view='watch-list'] to HTML
- [x] Add an empty ul element to this div
- [x] Add a list icon to the navbar
- [x] Listen for clicks on the list icon and
  - [x] Call switch views function to switch to 'watch-list' view
  - [x] Loop through data.watchlist and render each anime result with createResult function and prepend each to the ul element (so the most recently added appears at the top)
- [x] Add to clear results function so that it clears watch list view as well
- [x] Ensure view switches to 'watch-list' upon adding an anime from the 'search-results' view
- [x] Ensure page reloads to same view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
