### ISSUE TITLE
Feature: User can delete an anime from their watch list

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can delete an anime from their watch list

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will be able to delete an anime from their watch list by clicking a button and then confirming the deletion in pop up window. 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="139" alt="Screen Shot 2021-09-20 at 4 01 32 PM" src="https://user-images.githubusercontent.com/87718271/134087656-ffc3fa49-0e7d-40db-b181-5214fb2e823f.png">
<img width="138" alt="Screen Shot 2021-09-20 at 4 01 39 PM" src="https://user-images.githubusercontent.com/87718271/134087683-e8f4291d-594d-4cf1-a325-2061a9241e5d.png">
<img width="139" alt="Screen Shot 2021-09-20 at 4 01 44 PM" src="https://user-images.githubusercontent.com/87718271/134087696-7cf9e940-0484-4507-88f4-dd2886a2f62b.png">

<img width="292" alt="Screen Shot 2021-09-20 at 4 38 29 PM" src="https://user-images.githubusercontent.com/87718271/134090440-2126d69f-ae91-41de-8371-db1b08cd8501.png">

<img width="292" alt="Screen Shot 2021-09-20 at 4 38 33 PM" src="https://user-images.githubusercontent.com/87718271/134090449-41d55d84-d035-47a2-a57b-96d0d575f7ee.png">
<img width="293" alt="Screen Shot 2021-09-20 at 4 38 39 PM" src="https://user-images.githubusercontent.com/87718271/134090456-8ea229ed-a98a-4877-ae9b-29d6d5b983ef.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a condition to createResult() function to either add an 'add' or 'remove' button depending on the data.view
- [x] Listen for clicks on the watch-list ul and
  - [x] if the event.target is not a 'BUTTON' return
  - [x] loop through data.watchList
  - [x] if the value of the id attribute of the event.target matches mal_id of data.watchlist object, remove that li from the DOM and delete anime object in data.watchList
- [x] Ensure changes to local storage persist after reload
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
