### ISSUE TITLE
Feature: User can set priority to watch for an anime

### ISSUE THREAD

**Issue by aar-woo** [aar-woo/anime-log#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can set priority to watch for an anime

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can set a priority for each anime and view their watch list with the highest priority anime at the top.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="243" alt="Screen Shot 2021-09-20 at 4 33 06 PM" src="https://user-images.githubusercontent.com/87718271/134090015-c0552f57-327b-4e20-b53e-a73adb295066.png">
<img width="241" alt="Screen Shot 2021-09-20 at 4 33 12 PM" src="https://user-images.githubusercontent.com/87718271/134090023-e56711bf-0146-4334-8f5a-4a1ac9388dc3.png">

<img width="461" alt="Screen Shot 2021-09-20 at 4 34 19 PM" src="https://user-images.githubusercontent.com/87718271/134090104-2414a4c0-8fcf-445d-9dca-4ab86878ece5.png">
<img width="466" alt="Screen Shot 2021-09-20 at 4 34 35 PM" src="https://user-images.githubusercontent.com/87718271/134090108-5e52573d-989d-4433-be56-66369baad343.png">
## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add to createResult function to render result with "Priority: " and up arrow icons
- [x] Create CSS rules for empty (white) up arrows and filled (yellow) up arrows
- [x] Group arrow icons in a div
- [x] Give each arrow icon an id with value of a number, increasing for each arrow
- [x] Add a 'priority' property to each anime obj in watchList 
- [x] Get a nodelist of all the arrow icons
- [x] Listen to clicks on the watchList
  - [x] Find the closest li to event.target
  - [x] Loop through watchlist, if the mal_id of watchList item matches li's id, save to selectedAnime
  - [x] If the id of the event.target (clicked arrow) is less than the value in selectedAnime result's 'priority' property
    - [x] Loop through all nodelist of arrow icons and change each arrow icon class to empty, white arrows
  - [x] Loop through the nodelist of arrow icons up until the value of the id of the event.target
    - [x] Change each arrow icon's class to filled up arrows
  - [x] Set selectedAnime's 'priority' property to id of event.target
- [x] Add to renderWatchList function to render by each anime object's 'priority' property value
- [x] Ensure priority icons persist through reload
- [x] Ensure when adding an anime, the result appears on watch list with no priority set.
- [x] Add conditional to createResult function to only show priority on watch-list view
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
